[package]
name = "proton"
version = "0.1.0"
edition = "2024"

[dependencies]
half = "2.5.0"
libc = "0.2.172"
libffi = "4.0.0"
libloading = "0.8.6"

[[bin]]
name = "assembler"
path = "src/assembler/main.rs"

[[bin]]
name = "machine"
path = "src/machine/main.rs"
